pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Code already checked out automatically by Jenkins."
            }
        }

        stage('Build Frontend') {
            steps {
                dir('cloudcart/frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('cloudcart/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('cloudcart') {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Push to Registry') {
            steps {
                echo "Simulating push to Docker Registry..."
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                echo "Simulating deployment to AWS server..."
            }
        }
    }

    post {
        always {
            echo "Pipeline finished!"
        }
        success {
            echo "Deployment successful."
        }
        failure {
            echo "Deployment failed! Triggering alerts."
        }
    }
}
